### ISSUE TITLE
Common task list (August 2016)

### ISSUE THREAD

**Issue by Wohlstand** [WohlSoft/Moondust-Project#130]
- [ ] Reorganize PGE File Library to use classes with inheriting and polymorphism
- [ ] World map layers and events system. Make Action-styled events system NOW!
- [ ] Action-styled events for level subsystem
- [ ] Completed Read/Write implementation of SMBX-38A file formats support
- [ ] Implement [GFX Expansion system](https://github.com/WohlSoft/PGE-Project/issues/221) (allow custom image per individual element on the map)
# Manager
- [ ] Add getting of actual config packs list and showing up of the config pack info
- [ ] Implement downloading & installing of config packs (which is much required for Android and Mac OS X
  and for installer-less PGE packs to be user-friendly)
# Maintainer
- [x] Implement episode conversion (mass level and world maps converter)
- [x] Add ability to convert graphics and musics with mass levels and episodes too
- [x] Add automatic fixing of UNIX case sensitive file system compatibility for episodes (on the ext4, hfs with case sensitivity old SMBX Episodes which are accidentally designed for case insensitive FAT and NTFS file systems, may have misses of the some graphics and musics because in-file paths and real file names are not case with case sensitive. Fix that possible with collecting of all file names inside every level and world map, optionally in the config pack (image file-names), or just simply rename all filenames into low case, and rename all files to be case with declared paths)

**Comment by Wohlstand** [comment]
Closing as abandoned in favour of the completely new plan of Moondust Project rebuilding.
